In [1]:
import pandas as pd
import sklearn

In [2]:
df = pd.read_excel("test_podaci_aida.xlsx")

In [3]:
df.describe()

,Koliko imate godina,Koliko imate obroka dnevno?,Da li konzumirate UH,Da li ima plak na smociscenim povrsinama,Prisutan karijes na samociscenim povrÅ¡inama,Aktivne karijesne lezije,"Da li koristite neÅ¡to od navedenog (imterdendalna Äetkica, konac...)","Da li koristite nesto od navedenog : postao za zube , vodica za ispiranje usta",Koliko Äesto Äekate zube,RIZIK
count,20,20,20,20,20,20,20,20,20,20
unique,2,3,2,2,2,2,2,2,4,5
top,Manje od 6,5,Da,Da,Da,Ne,Ne,Da,Poslije svakog obroka,niski
freq,11,8,11,10,11,12,11,10,7,8

In [4]:
df.head()

,Koliko imate godina,Koliko imate obroka dnevno?,Da li konzumirate UH,Da li ima plak na smociscenim povrsinama,Prisutan karijes na samociscenim povrÅ¡inama,Aktivne karijesne lezije,"Da li koristite neÅ¡to od navedenog (imterdendalna Äetkica, konac...)","Da li koristite nesto od navedenog : postao za zube , vodica za ispiranje usta",Koliko Äesto Äekate zube,RIZIK
0,ViÅ¡e od 6,ViÅ¡e od 5,Da,Da,Da,Ne,Ne,Da,Poslije svakog obroka,vioski
1,Manje od 6,5,Da,Ne,Da,Ne,Ne,Ne,Poslije svakog obroka,srednji
2,ViÅ¡e od 6,5,Ne,Da,Ne,Ne,Ne,Da,Dvaput dnevno,niski
3,ViÅ¡e od 6,5,Ne,Da,Da,Da,Ne,Da,Jedanput dnevno,niski
4,ViÅ¡e od 6,ViÅ¡e od 5,Ne,Ne,Ne,Ne,Da,Ne,Poslije svakog obroka,niski

In [7]:
def map(x):
    if x == "Da":
        return 1 
    return 0

def korekcijaRizika(x):
    if x[0] == 'v':
        return "visoki"
    elif x[0] == 's':
        return "srednji"
    return "niski"
    
    
brojac = 1
rename_dict = {}
for col in df.columns:
    if col != "RIZIK":
        rename_dict[col] = "Q"+str(brojac)
        brojac += 1
df = df.rename(columns=rename_dict)

In [8]:
df.head()

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,RIZIK
0,ViÅ¡e od 6,ViÅ¡e od 5,Da,Da,Da,Ne,Ne,Da,Poslije svakog obroka,vioski
1,Manje od 6,5,Da,Ne,Da,Ne,Ne,Ne,Poslije svakog obroka,srednji
2,ViÅ¡e od 6,5,Ne,Da,Ne,Ne,Ne,Da,Dvaput dnevno,niski
3,ViÅ¡e od 6,5,Ne,Da,Da,Da,Ne,Da,Jedanput dnevno,niski
4,ViÅ¡e od 6,ViÅ¡e od 5,Ne,Ne,Ne,Ne,Da,Ne,Poslije svakog obroka,niski

In [11]:
df = df.dropna(subset=['RIZIK'])

In [12]:
df['RIZIK'] = df['RIZIK'].apply(lambda x: korekcijaRizika(x))
df['Q3'] = df['Q3'].apply(lambda x: map(x))
df['Q4'] = df['Q4'].apply(lambda x: map(x))
df['Q5'] = df['Q5'].apply(lambda x: map(x))
df['Q6'] = df['Q6'].apply(lambda x: map(x))
df['Q7'] = df['Q7'].apply(lambda x: map(x))
df['Q8'] = df['Q8'].apply(lambda x: map(x))

In [13]:
df.head()

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,RIZIK
0,ViÅ¡e od 6,ViÅ¡e od 5,1,1,1,0,0,1,Poslije svakog obroka,visoki
1,Manje od 6,5,1,0,1,0,0,0,Poslije svakog obroka,srednji
2,ViÅ¡e od 6,5,0,1,0,0,0,1,Dvaput dnevno,niski
3,ViÅ¡e od 6,5,0,1,1,1,0,1,Jedanput dnevno,niski
4,ViÅ¡e od 6,ViÅ¡e od 5,0,0,0,0,1,0,Poslije svakog obroka,niski

In [14]:
one_hot = pd.get_dummies(df['Q1'])
df = df.drop('Q1',axis = 1)
df = df.join(one_hot)

one_hot = pd.get_dummies(df['Q2'])
df = df.drop('Q2',axis = 1)
df = df.join(one_hot)

one_hot = pd.get_dummies(df['Q9'])
df = df.drop('Q9',axis = 1)
df = df.join(one_hot)

In [15]:
pd.set_option('display.max_columns', None)

In [16]:
df.columns

Index([                      'Q3',                       'Q4',
                             'Q5',                       'Q6',
                             'Q7',                       'Q8',
                          'RIZIK',               'Manje od 6',
                     'ViÅ¡e od 6',                          3,
                                5,               'ViÅ¡e od 5',
                  'Dvaput dnevno',          'Jedanput dnevno',
       'Manje od jedanput dnevno',    'Poslije svakog obroka'],
      dtype='object')

In [17]:
df.head(20)

,Q3,Q4,Q5,Q6,Q7,Q8,RIZIK,Manje od 6,ViÅ¡e od 6,3,5,ViÅ¡e od 5,Dvaput dnevno,Jedanput dnevno,Manje od jedanput dnevno,Poslije svakog obroka
0,1,1,1,0,0,1,visoki,False,True,False,False,True,False,False,False,True
1,1,0,1,0,0,0,srednji,True,False,False,True,False,False,False,False,True
2,0,1,0,0,0,1,niski,False,True,False,True,False,True,False,False,False
3,0,1,1,1,0,1,niski,False,True,False,True,False,False,True,False,False
4,0,0,0,0,1,0,niski,False,True,False,False,True,False,False,False,True
5,0,0,1,0,1,1,niski,False,True,False,True,False,False,False,False,True
6,1,1,1,1,0,0,visoki,False,True,False,False,True,False,False,True,False
7,1,0,0,1,0,1,niski,True,False,True,False,False,True,False,False,False
8,1,0,0,0,0,0,visoki,True,False,False,True,False,False,False,True,False
9,1,1,0,0,0,0,visoki,False,True,True,False,False,False,True,False,False
10,1,1,1,1,1,1,visoki,True,False,False,True,False,False,False,False,True
11,0,0,0,0,1,0,niski,True,False,False,False,True,False,True,False,False
12,0,1,1,1,1,0,visoki,True,False,True,False,False,True,False,False,False
13,0,1,1,1,1,0,visoki,True,False,False,True,False,False,True,False,False
14,1,0,1,0,1,0,visoki,True,False,False,False,True,False,False,False,True
15,0,1,0,0,1,1,niski,True,False,True,False,False,True,False,False,False
16,1,1,0,0,0,1,visoki,False,True,False,True,False,False,False,True,False
17,1,0,1,0,0,1,visoki,True,False,False,False,True,False,False,True,False
18,1,0,1,1,1,1,srednji,True,False,True,False,False,False,False,False,True
19,0,0,0,1,0,0,niski,False,True,True,False,False,False,True,False,False

In [18]:
df['RIZIK']

0      visoki
1     srednji
2       niski
3       niski
4       niski
5       niski
6      visoki
7       niski
8      visoki
9      visoki
10     visoki
11      niski
12     visoki
13     visoki
14     visoki
15      niski
16     visoki
17     visoki
18    srednji
19      niski
Name: RIZIK, dtype: object

In [19]:
print(df.isnull().sum())

Q3                          0
Q4                          0
Q5                          0
Q6                          0
Q7                          0
Q8                          0
RIZIK                       0
Manje od 6                  0
ViÅ¡e od 6                  0
3                           0
5                           0
ViÅ¡e od 5                  0
Dvaput dnevno               0
Jedanput dnevno             0
Manje od jedanput dnevno    0
Poslije svakog obroka       0
dtype: int64

In [20]:
df.columns

Index([                      'Q3',                       'Q4',
                             'Q5',                       'Q6',
                             'Q7',                       'Q8',
                          'RIZIK',               'Manje od 6',
                     'ViÅ¡e od 6',                          3,
                                5,               'ViÅ¡e od 5',
                  'Dvaput dnevno',          'Jedanput dnevno',
       'Manje od jedanput dnevno',    'Poslije svakog obroka'],
      dtype='object')

In [21]:
df = df.rename(columns={3:"tri", 5: "pet"})

In [22]:
df.columns

Index(['Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'RIZIK', 'Manje od 6', 'ViÅ¡e od 6',
       'tri', 'pet', 'ViÅ¡e od 5', 'Dvaput dnevno', 'Jedanput dnevno',
       'Manje od jedanput dnevno', 'Poslije svakog obroka'],
      dtype='object')

In [23]:
X = df.loc[:, df.columns != 'RIZIK']
y = df['RIZIK']

In [24]:
y.isnull().sum()

0

In [25]:
y.head()

0     visoki
1    srednji
2      niski
3      niski
4      niski
Name: RIZIK, dtype: object

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=40)
clf = LogisticRegression(random_state=0, multi_class="multinomial")
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.75